[build]
functions="src"
functionsSource="src"
command="npm i src/stripe-charge/; npm i src/stripe-subscription/"

[context.production.environment]
STRIPE_SECRET_KEY="prod_12345"

[context.deploy_preview.environment]
STRIPE_SECRET_KEY="dev_12345"
